name = "pansou-tg-bot"
main = "index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "pansou-tg-bot"

[env.staging]
name = "pansou-tg-bot-staging"

# 环境变量配置
[vars]
# 在 Cloudflare Workers 控制台中设置这些环境变量
# TELEGRAM_BOT_TOKEN = "your_bot_token"
# PANSOU_API_URL = "https://find.966001.xyz"
